### PR TITLE
Pandas feature

### PR DESCRIPTION
**Pull request by pielco11**

### CODE REVIEW

**Comment by pielco11** [comment]
#132

**Comment by louisgregg** [comment]
Hi, 
I am trying to output twint scraping results directly to a Pandas dataframe without writing to disk. I have read the discussion on isssue #132 which states:

> You can use the twint.Pandas.get() method to get the Dataframe, use twint.Pandas.save() to save (see arguments of the method) and the same to read from saved Dataframe

> **You do not have to write to a file to operate with the Dataframe**

I'm using a recent version of twint and Python 3.6.7, but the dataframe output does not work. 
Here is the code I'm using: 
`# Import the module
import twint

# Set up TWINT config
c = twint.Config()
c.Search = "Fruit"
c.Limit = 20
c.Pandas = True
c.Pandas_clean = True
c.Lang = "en"

# Start search
twint.run.Search(c)

# check dataframe output
output = twint.Pandas.get()
print(output)
type(output)`

And the resultant error: 
`Traceback (most recent call last):
  File "test.py", line 19, in <module>
    output = twint.Pandas.get()
AttributeError: module 'twint' has no attribute 'Pandas'`

Does twint still support direct output to dataframe, without saving to a file? And if so, what method do I need to call to achieve this? 

Thanks very much,
Louis

**Comment by pielco11** [comment]
Hi @louisgregg 

the code changed a bit since this PR. Now as now, you should code something like

```python
import twint

c = twint.Config() 
c.Pandas = True 
c.Username = 'noneprivacy' 
c.Limit = 20

twint.run.Search(c) 
df = twint.storage.panda.Tweets_df 
```

**Comment by louisgregg** [comment]
Awesome, that worked. Thank you for clarifying this.

**Pull request merged**
