### PR TITLE
adding mysql support 

### PR DESCRIPTION
**Pull request by Nestor75**
I have added also all the changes in version 1.1.3.4 plus mysql support
the mysql database schema and tables is also included

### CODE REVIEW

**Comment by pielco11** [comment]
Hmm, there are conflicts in those files. I suggest you to:

- sync from upstream/master (haccer/twint);
- add the work that you done to implement MySQL;
- push to your fork (everything will automatically be showed here, so no need to create pull requests or stuff).

Github will automatically should you where the conflicts are, look around to see how to solve them. If you get stuck up feel free to let us know!

**Comment by Nestor75** [comment]
I will follow your guides and I hope don't bother you with many questions about this stuff and publish the code ;)

**Comment by haccer** [comment]
Thank you @Nestor75

**Comment by Nestor75** [comment]
HI All , 

After tones of tries I think I finally got it. 
Could you please review it and merge it if there is everything ok?

many thanks

**Comment by pielco11** [comment]
Will try that asap, thank you so much for your work!

**Comment by Nestor75** [comment]
I like your work a lot and I adapt it to my needs so the best way to contribute... even I am not a python expert... it's sharing the modifications I did with all of you.

**Comment by pielco11** [comment]
I see some `SyntaxError` around, for example in `Twint.py` at line 35. I suggest you to run `python -m py_compile Twint.py`, and the same for others to find out quickly `SyntaxError`s, to avoid passing line by line

**Comment by Nestor75** [comment]
My fault , the parameters check was the last thing I included and to be honest I did not check it, I will review it and I will come back to you

**Comment by haccer** [comment]
Awesome @Nestor75

**Comment by haccer** [comment]
There's a few things I need to edit before I merge to make sure things don't break. I'll look at this more later tonight.

**Comment by Nestor75** [comment]
many thanks :) I fixed the syntax errors I made , I run the test.py but using the mysql parameters instead the sqlite3 and it works perfect. 
What I did not test is with a SQLITE3 database.... I am so tired now so..... it will be much better doing it tomorrow.

**Comment by haccer** [comment]
Thanks @Nestor75 !

I'll merge after Travis-CI finishes building

**Pull request merged**
