### PR TITLE
find the Guest token in HTML

### PR DESCRIPTION
**Pull request by ajctrl**
fix issue #1061

### CODE REVIEW

**Comment by karinorz** [comment]
why the patch-1 has to be deleted? I got error message due to it

WARNING: Did not find branch or tag 'patch-1', assuming revision or ref.

**Comment by CuFFaz** [comment]
> 

Did you find a workaround to this?

**Comment by Zenilos** [comment]
I have the same isuue from 2 weeks ago.

**Comment by Silvthril** [comment]
Really need to figure the solution to this ```twint.token.RefreshTokenException: Could not find the Guest token in HTML```

**Comment by Zenilos** [comment]
you can use this pr: https://github.com/Museum-Barberini/twint/tree/fix/RefreshTokenException

**Comment by harishthipparthy** [comment]
Should i run token.py?

**Comment by Silvthril** [comment]
> you can use this pr: https://github.com/Museum-Barberini/twint/tree/fix/RefreshTokenException

Ty for the suggestion. I'm a bit of a GitHub noobie. How can I update Twint properly with the link you provided?

I tried just copying the token.py file found in the link you gave but I broke it worse so I reverted the changes.

**Comment by Silvthril** [comment]
I tried switching the branches on my local machine with ```git checkout -b Fix/RefreshTokenException``` which results in successfully switching branches message ```Switched to a new branch 'fix/RefreshTokenException'```.

However after running a simple twint command such as ```python twint -s "apple"``` the result is the same as prior to switching from the Master branch ```  File "/home/ark/Tools/tradecraft/OSINT/Twint/twint", line 33, in <module>
    sys.exit(load_entry_point('twint==2.1.21', 'console_scripts', 'twint')())
  File "/home/ark/Tools/tradecraft/OSINT/Twint/src/twint/twint/cli.py", line 339, in run_as_command
    main()
  File "/home/ark/Tools/tradecraft/OSINT/Twint/src/twint/twint/cli.py", line 330, in main
    run.Search(c)
  File "/home/ark/Tools/tradecraft/OSINT/Twint/src/twint/twint/run.py", line 410, in Search
    run(config, callback)
  File "/home/ark/Tools/tradecraft/OSINT/Twint/src/twint/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/home/ark/Tools/tradecraft/OSINT/Twint/src/twint/twint/run.py", line 36, in __init__
    self.token.refresh()
  File "/home/ark/Tools/tradecraft/OSINT/Twint/src/twint/twint/token.py", line 69, in refresh
    raise RefreshTokenException('Could not find the Guest token in HTML')
twint.token.RefreshTokenException: Could not find the Guest token in HTML```

A tidbit more information on my particular install >> I use Garuda Linux; Love it! I installed twint via pip over 6 months ago. I wanted to utilize it in a more accessible file rather than navigating to the ```.local/bin/src``` location where my setup installs pip programs. To achieve this I created a simple directory as you can see in the output above that contains a symlink to the ```.local/bin/src``` location. 

This issue started a few weeks ago. I use two text files and a loop.sh program to loop search terms together I call '''keywords''' & ```catalysts``` in order to have a nice boolean feature with this program. It worked great for a long time. Then out of about 100 or so search term pairs about 10% would hit this error listed above. A few days ago I was running a simple task just ```python twint -s "keyword"``` where I would have to attempt to run the command about 5 times before it would run passing through his ```GuestToken``` error. Yesterday and today it's completely useless and I can't find a workaround or perhaps I'm not knowledgeable enough to effectively understand/utilize a workaround that may exist.

**Comment by Silvthril** [comment]
SOLVED:

Ok. So what I did in my initial comment ```copying the token.py file found @ https://github.com/Museum-Barberini/twint/tree/fix/RefreshTokenException``` did not work because I edited the token.py file at the ```.local/bin/src``` location described in my second comment. This is because, as mentioned the location I run the program out of (and surprisingly even if I try running twint out of the ```.local/bin/src``` location) runs the program out of the directory I made where there is a symlink pointing to that ```.local/bin/src``` location. Now, this is just a hunch based on the solution I discovered which I will list below but I think that this did not work because I would need to have updated the symlink? 

What solved the problem was repeating the same thing but this time I updated the ```src``` file located in the directory I created ```home/ark/Tools/tradecraft/OSINT/Twint/twint``` >> full path to ```token.py``` >> ```/home/ark/Tools/tradecraft/OSINT/Twint/src/twint/twint``` << << 

Now, why do I need the twint src code in this directory if it should be retrieving the src code from the symlink I created? I have no idea BUT twint wont work PERIOD in this easier to navigate to directory without both the symlink and the code contained within. Super strange I set it up over 6 months ago so I don't recall why I had to do this but yeah. There it is.  Thank you for your help @MINIMALaq !

SOLUTION SUMMARY: 

Overwrite your existing ```token.py``` file with the file contents contained here: https://github.com/Museum-Barberini/twint/blob/fix/RefreshTokenException/twint/token.py

**Pull request merged**
